name: PHPStan Static Analysis

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  larastan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: json

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run Larastan (PHPStan)
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon --level=9
